# Generated by Django 5.0 on 2024-08-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_remove_userprofile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Register',
        ),
    ]
