# Generated by Django 5.0 on 2024-08-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_rename_userprofile_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
