# Generated by Django 5.0 on 2024-09-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_alter_registeruser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registeruser',
        ),
    ]
