# Generated by Django 5.0 on 2024-09-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
