# Generated by Django 5.0 on 2024-09-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_crop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crop',
        ),
    ]
