# Generated by Django 5.0 on 2024-09-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_crop_cropimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropimage',
            name='crop',
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='CropImage',
        ),
    ]
